site_name: MagicPods Help
nav:
  - Getting started: index.md
  - Bluetooth: 'bt-bluetooth.md'
  - MagicAAP driver: fun-magicaap.md
  - 'Features':
    - Live tiles: fun-live-tiles.md
    - Widgets: fun-widgets.md
    - Change image: headphones-change-image.md
    - 'Headphones':
      - Other headphones: headphones/other-headphones.md
      - AirPods 1-2: headphones/apple-airpods12.md
      - AirPods 3: headphones/apple-airpods3.md
      - AirPods Max: headphones/apple-airpodsmax.md
      - AirPods Pro: headphones/apple-airpodspro.md
      - AirPods Pro 2: headphones/apple-airpodspro2.md
      - Beats Fit Pro: headphones/apple-beatsfitpro.md
      - Beats Flex: headphones/apple-beatsflex.md
      - Beats Solo 3: headphones/apple-beatssolo3.md
      - Beats Solo Pro: headphones/apple-beatssolopro.md
      - Beats Studio 3: headphones/apple-beatsstudio3.md
      - Beats Studio Buds: headphones/apple-beatsstudiobuds.md
      - Beats Studio Buds Plus: headphones/apple-beatsstudiobudsplus.md
      - Beats X: headphones/apple-beatsx.md
      - Power Beats 3: headphones/apple-powerbeats3.md
      - Power Beats 4: headphones/apple-powerbeats4.md
      - Power Beats Pro: headphones/apple-powerbeatspro.md
      - Sony WF-1000XM3: headphones/sony-wf1000xm3.md
      - Sony WH-1000XM4: headphones/sony-wh1000xm4.md
      - Fake AirPods Pro 2 Airoha 1562AE: headphones/airoha-airpodspro2-1562ae.md
      - Fake AirPods Pro Airoha 1562AE: headphones/airoha-airpodspro-1562ae.md
      - Fake AirPods 3 Airoha 1562E: headphones/airoha-airpods3-1562e.md

    - 'General settings':
      - Pop-up window: fun-popup-animation.md
      - Sound output: fun-sound-output.md
      - Audio streaming: fun-audio-streaming.md
      - VoiceOver: fun-audio.md
      - System tray icon: fun-tray-icon.md
    - 'Preferences':
      - Application settings: pref-app-settings.md
    - Pair headphones: help-pairing-headphones.md

  - 'Resolving known issues':
    - Infinite search: issue-infinite-search.md
    - Poor sound and mic quality: issue-mic-low-quality.md
    - Infinite disconnect: issue-infinite-disconnect.md
    - AirPods status not updating: issue-airpods-status-not-updating.md
    - Tray icon is too dark: issue-theme.md
    - Connectivity issues: issue-connectivity.md
    - Bluetooth LE not supported: issue-ble-not-supported.md
    - Switch audio output not available: issue-switch-audio-not-available.md
    - Сrashes at start: issue-crashes-at-start.md

  - Translate: translate.md 
  - Report issue: report-issue.md
  - Changelog: changelog.md

theme:
  name: material
  favicon: media/favicon.svg
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"        
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode   
 
  font:
    text: Rubik
  logo: media/favicon.svg 
  features:
    - navigation.expand
    - navigation.top

    - header.autohide
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: ⚓︎
      toc_depth: 3
site_url:
  https://help.magicpods.app/

plugins:
  - include-markdown

exclude_docs: |
  features/
  issues/