site_name: MagicPods Help
nav:
  - Getting started: index.md
  - Bluetooth: 'bt-bluetooth.md'
  - MagicAAP (Official): fun-magicaap.md
  - MagicAAP (Community): fun-magicaap-community.md
  - 'Features':
    - Live tiles: fun-live-tiles.md
    - Widgets: fun-widgets.md
    - Change image: headphones-change-image.md
    - 'Headphones':
      - Other headphones: headphones/other-headphones.md
      - AirPods 1-2: headphones/apple-airpods12.md
      - AirPods 3: headphones/apple-airpods3.md
      - AirPods 4: headphones/apple-airpods4.md
      - AirPods 4 (ANC): headphones/apple-airpods4-anc.md
      - AirPods Max: headphones/apple-airpodsmax.md
      - AirPods Max 2024: headphones/apple-airpodsmax2024.md
      - AirPods Pro: headphones/apple-airpodspro.md
      - AirPods Pro 2: headphones/apple-airpodspro2.md
      - AirPods Pro 3: headphones/apple-airpodspro3.md
      - Beats Fit Pro: headphones/apple-beatsfitpro.md
      - Beats Flex: headphones/apple-beatsflex.md
      - Beats Solo 3: headphones/apple-beatssolo3.md
      - Beats Solo Pro: headphones/apple-beatssolopro.md
      - Beats Solo Buds: headphones/apple-beatssolobuds.md
      - Beats Studio 3: headphones/apple-beatsstudio3.md
      - Beats Studio Pro: headphones/apple-beatsstudiopro.md
      - Beats Studio Buds: headphones/apple-beatsstudiobuds.md
      - Beats Studio Buds Plus: headphones/apple-beatsstudiobudsplus.md
      - Beats X: headphones/apple-beatsx.md
      - Powerbeats 3: headphones/apple-powerbeats3.md
      - Powerbeats 4: headphones/apple-powerbeats4.md
      - Powerbeats Pro: headphones/apple-powerbeatspro.md
      - Powerbeats Pro 2: headphones/apple-powerbeatspro2.md
      - Sony WF-1000XM3: headphones/sony-wf1000xm3.md
      - Sony WH-1000XM4: headphones/sony-wh1000xm4.md
      - Fake AirPods Pro 2 Airoha 1571AM: headphones/airoha-airpodspro2-1571am.md
      - Fake AirPods Pro 2 Airoha 1562AE: headphones/airoha-airpodspro2-1562ae.md
      - Fake AirPods Pro Airoha 1562AE: headphones/airoha-airpodspro-1562ae.md
      - Fake AirPods 3 Airoha 1562E: headphones/airoha-airpods3-1562e.md
      - Galaxy Buds: headphones/galaxy-buds.md
      - Galaxy Buds Plus: headphones/galaxy-buds-plus.md
      - Galaxy Buds Live: headphones/galaxy-buds-live.md
      - Galaxy Buds Pro: headphones/galaxy-buds-pro.md
      - Galaxy Buds 2: headphones/galaxy-buds-2.md
      - Galaxy Buds 2 Pro: headphones/galaxy-buds-2-pro.md
      - Galaxy Buds Fe: headphones/galaxy-buds-fe.md
      - Galaxy Buds 3: headphones/galaxy-buds-3.md
      - Galaxy Buds 3 Pro: headphones/galaxy-buds-3-pro.md

    - 'General settings':
      - Pop-up window: fun-popup-animation.md
      - Sound output: fun-sound-output.md
      - Audio streaming: fun-audio-streaming.md
      - VoiceOver: fun-audio.md
      - System tray icon: fun-tray-icon.md
    - 'Hotkeys':
      - Bluetooth: fun-hotkeys-bluetooth.md
      - Headphones: fun-hotkeys-headphones.md
      - Sound output: fun-hotkeys-sound-output.md
      - VoiceOver: fun-hotkeys-voiceover.md
      - Audio streaming: fun-hotkeys-audio-streaming.md
    - 'Preferences':
      - Application settings: pref-app-settings.md

  - 'Help articles':
    - H2 chip behavior: help-h2-chip.md
    - Identify fake AirPods: info-fake-headphones.md
    - Pair headphones: help-pairing-headphones.md

  - 'Known issues':
    - Infinite search: issue-infinite-search.md
    - Poor sound and mic quality: issue-mic-low-quality.md
    - Startup disabled by group policy: issue-startup-disabled-by-group-policy.md
    - Infinite disconnect: issue-infinite-disconnect.md
    - AirPods status not updating: issue-airpods-status-not-updating.md
    - Tray icon is too dark: issue-theme.md
    - Connectivity issues: issue-connectivity.md
    - Bluetooth LE not supported: issue-ble-not-supported.md
    - Switch audio output not available: issue-switch-audio-not-available.md
    - Crashes at start: issue-crashes-at-start.md

  - Translate: translate.md 
  - Report issue: report-issue.md
  - Changelog: changelog.md

theme:
  name: material
  favicon: media/favicon.svg
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"        
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode   
 
  font:
    text: Rubik
  logo: media/favicon.svg 
  features:
    - navigation.expand
    - navigation.top

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - sane_lists
  - toc:
      permalink: ⚓︎
      toc_depth: 4
site_url:
  https://help.magicpods.app/

plugins:
  - include-markdown
  - search

exclude_docs: |
  features/
  issues/