site_name: MagicPods Help
nav:
  - Home: index.md
  - 'Bluetooth':
    - Requirements: 'bt-requirements.md'
    - Adapter not found: "bt-adapter-not-found.md"
    - Multiple adapters connected: "bt-multiple-adapters-connected.md"
    - Adapter initialization error: "bt-adapter-initialization-error.md"
    - Classic not supported: "bt-classic-not-supported.md"
    - LE not supported: "bt-le-not-supported.md"
  - 'Functions':
    - Capability: fun-capability.md
    - 'Headphones':
      - Change image: headphones-change-image.md
      - Show battery percentage: headphones-show-battery-percentage.md
      - Low audio latency: headphones-low-audio-latency.md
      - Auto play: headphones-auto-play.md
      - Auto pause: headphones-auto-pause.md
      - Auto disable Handsfree: headphones-auto-disable-hfp.md  
      - Low battery notification: headphones-low-battery-notification.md 
      - Auto switch sound output: headphones-auto-switch-sound-output.md
      - Connect hotkey: headphones-hotkey-connect.md
      - "AirPods / Beats":
        - Ear Detection: headphones-ear-detection.md
        - Fast search: headphones-fast-search.md
        - Auto connect: headphones-auto-connect.md
      - "Sony":
        - Noise cancelling: headphones-sony-anc.md
      - "Fake Airoha AirPods":
        - Chip Firmware: "headphones-airoha-chip.md" 
        - Ear Detection: headphones-airoha-ear-detection.md
        - Noise cancelling: headphones-airoha-anc.md
        - Head tracking: headphones-airoha-head-tracking.md
        - Earbuds keys: headphones-airoha-earbuds-keys.md
        - Case sounds: headphones-airoha-case-sounds.md
        - Multipoint connection: headphones-airoha-multipoint-connection.md
        - Wind noise reduction: headphones-airoha-wnr.md
        - Voice control: headphones-airoha-voice-control.md
        - Equalizer: headphones-airoha-equalizer.md
        - Game mode: headphones-airoha-game-mode.md
    - 'General settings':
      - Pop-up window: fun-popup-animation.md
      - Sound output: fun-sound-output.md
      - Audio streaming: fun-audio-streaming.md
      - VoiceOver: fun-audio.md
      - System tray icon: fun-tray-icon.md
    - 'Preferences':
      - Application settings: pref-app-settings.md
    - Icons description: fun-icons-description.md
    - Pair headphones: help-pairing-headphones.md

  - 'Headphones':
    - Fake headphones warning: info-fake-headphones.md

  - 'Resolving known issues':
    - Infinite search: issue-infinite-search.md
    - Infinite disconnect: issue-infinite-disconnect.md
    - AirPods status not updating: issue-airpods-status-not-updating.md
    - Tray icon is too dark: issue-theme.md
    - Connectivity issues: issue-connectivity.md
    - Bluetooth LE not supported: issue-ble-not-supported.md
    - Switch audio output not available: issue-switch-audio-not-available.md
    - Сrashes at start: issue-crashes-at-start.md

  - Translate: translate.md 
  - Report issue: report-issue.md
  - Changelog: changelog.md

theme:
  name: material
  favicon: media/favicon.svg
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"        
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode   
 
  font:
    text: Rubik
  logo: media/favicon.svg 
  features:
    - navigation.expand
    - navigation.top

    - header.autohide
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
site_url:
  https://help.magicpods.app/
